parameters:
  wechat:
    get_code_url: https://open.weixin.qq.com/connect/oauth2/authorize
    get_access_token_url: https://api.weixin.qq.com/sns/oauth2/access_token
    get_user_info_url: https://api.weixin.qq.com/sns/userinfo




